#!/bin/python3

import math
import os
import random
import re
import sys

# Complete the poisonousPlants function below.
def poisonousPlants(p):
    inf, ans = float('inf' ), 0 
    stack = [[-inf, inf, inf]] 
    for i in p:
        while stack[-1][0] >= i or stack[-1][1] - stack[-1][2] == 0:
            stack.pop() 
        if i > stack[-1][0] and stack[-1][0] != -inf:
            stack[-1][1] += 1 
            ans = max(ans, stack[-1][1])
        stack.append([i, 0, stack[-1][1]] ) 
    return ans

if __name__ == '__main__':
    fptr = open(os.environ['OUTPUT_PATH'], 'w')

    n = int(input())

    p = list(map(int, input().rstrip().split()))

    result = poisonousPlants(p)

    fptr.write(str(result) + '\n')

    fptr.close()
