#!/bin/python3

import math
import os
import random
import re
import sys

# Complete the catAndMouse function below.
def catAndMouse(x, y, z):
    catAresult = math.fabs(x-z)
    catBresult = math.fabs(y-z)
    if catAresult == catBresult:
        return 'Mouse C'
    elif catAresult < catBresult:
        return 'Cat A'
    elif catBresult < catAresult:
        return 'Cat B'

if __name__ == '__main__':
    fptr = open(os.environ['OUTPUT_PATH'], 'w')

    q = int(input())

    for q_itr in range(q):
        xyz = input().split()

        x = int(xyz[0])

        y = int(xyz[1])

        z = int(xyz[2])

        result = catAndMouse(x, y, z)

        fptr.write(result + '\n')

    fptr.close()
