#!/bin/python3

import math
import os
import random
import re
import sys

# Complete the flippingBits function below.
def flippingBits(n):
    n_bi = bin(n)
    temp = ''
    for i in n_bi[2:]:
        if i == '1':
            temp += '0'
        else:
            temp += '1'
    temp = (32 - len(temp))*'1' + temp
    return int(temp,2)

if __name__ == '__main__':
    fptr = open(os.environ['OUTPUT_PATH'], 'w')

    q = int(input())

    for q_itr in range(q):
        n = int(input())

        result = flippingBits(n)

        fptr.write(str(result) + '\n')

    fptr.close()
