#!/bin/python3

import math
import os
import random
import re
import sys

# Complete the migratoryBirds function below.
def migratoryBirds(arr):
    Type = []
    Type.append(arr.count(1))
    Type.append(arr.count(2))
    Type.append(arr.count(3))
    Type.append(arr.count(4))
    Type.append(arr.count(5))

    return Type.index(max(Type))+1

if __name__ == '__main__':
    fptr = open(os.environ['OUTPUT_PATH'], 'w')

    arr_count = int(input().strip())

    arr = list(map(int, input().rstrip().split()))

    result = migratoryBirds(arr)

    fptr.write(str(result) + '\n')

    fptr.close()
