#!/bin/python3

import math
import os
import random
import re
import sys

#
# Complete the 'pickingNumbers' function below.
#
# The function is expected to return an INTEGER.
# The function accepts INTEGER_ARRAY a as parameter.
#

def pickingNumbers(a):
    # Write your code here
    l= len(a)
    c=[]
    max_len = []
    for i in range(l):
        c.append([])
        for j in range(l):
            if a[i] == a[j] or a[i]+1== a[j]:
                c[i].append(a[j])
    for i in range(l):
        max_len.append(len(c[i]))
    return max(max_len)

if __name__ == '__main__':
    fptr = open(os.environ['OUTPUT_PATH'], 'w')

    n = int(input().strip())

    a = list(map(int, input().rstrip().split()))

    result = pickingNumbers(a)

    fptr.write(str(result) + '\n')

    fptr.close()
