#!/bin/python3

import math
import os
import random
import re
import sys

# Complete the primality function below.
def primality(n):
    result = ["Not prime","Prime"]
    if n == 1:
        return result[0]
    for i in range(2,int(math.sqrt(n)+1)):
        if n % i == 0:
            return result[0]
    return result[1]

if __name__ == '__main__':
    fptr = open(os.environ['OUTPUT_PATH'], 'w')

    p = int(input())

    for p_itr in range(p):
        n = int(input())

        result = primality(n)

        fptr.write(result + '\n')

    fptr.close()
